apiVersion: apps/v1
kind: Deployment
metadata:
  name: memorialcontext
  labels:
    app: memorialcontext
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memorialcontext
  template:
    metadata:
      labels:
        app: memorialcontext
    spec:
      containers:
        - name: memorialcontext
          image: "a071098registry.azurecr.io/memorialcontext:v1"
          ports:
            - containerPort: 8080
          # [추가] secret.yaml에 정의된 값들을 환경 변수로 주입합니다.
          envFrom:
            - secretRef:
                name: api-keys
            - configMapRef:
                name: my-configs
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 10
            failureThreshold: 30
