# ========================================
# FILENAME: aivlebigproject/kubernetes/secret.yaml
# ========================================

apiVersion: v1
kind: Secret
metadata:
  name: api-keys
type: Opaque
data:
  # OpenAI API
  OPENAI_API_KEY: "c2stcHJvai1EMFRka1lQRlRLeWxyV2hNYTZ5SDhnQUx2QnVnZWZ3TkVsOUYyUXotblJpLWx5eFBxMFZYcmN0eC1uUFpuck5wM2hURnVkQ1JnOVQzQmxia0ZKa3IzNDZaZDV2aXQ5ZUI5ZFhwR3FTRXZESHgtRHdRdU5oVF9GQ19EbWxLbUk4VS1jUEh1eVlxZGE1QUtnMkR4ai03ZnF6UDcwSUE="
  # AzureMySQL DB
  AZURE_MYSQL_DB_PASSWORD: "YTA3MTA5OEFpdmxl"
  # AzureBlob Python(funeralcontext)
  AZURE_STORAGE_CONNECTION_STRING: "RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPWEwNzEwOThibG9idGVzdDtBY2NvdW50S2V5PUt0WndJMzdRaUE2SnJQaFRqaEN2cWFFZC9wYWY2aXdCS3NBcTVqYi9tYUlNeEtwaFF1cldpSkRUejVrTmtWTmMwd0QvSXovOEZHeFUrQVN0MkkvU0xBPT07RW5kcG9pbnRTdWZmaXg9Y29yZS53aW5kb3dzLm5ldA=="
  # AzureBlob Java(memorialcontext)
  AZURE_STORAGE_ACCOUNT_KEY: "VFV3RmZVdTE0YktWblBpMEhBQlN3Mm10Y1NpZnlyUHdrbS9haVBmbXE3V1BPQ0xuYjJDMVdVak51dDF0b3kvdVh2OURhblcxSEhJcitBU3RHbTM1TWc9PQ=="
